/**
 * Boolean circuits: size is area and depth is latency.
 *
 * That reading is the whole practical content of the section, and it is the
 * same trade a real ALU makes physically — a ripple-carry adder is small and
 * deep, a carry-lookahead adder is large and shallow, and the choice is
 * exactly the choice between size and depth here.
 *
 * The theoretical content is non-uniformity. A circuit works for ONE input
 * length, so a "circuit family" is a different object per n, and nothing
 * requires the family to be generated by any program. That is why P/poly
 * contains undecidable languages: a family can encode the answer to an
 * undecidable question one bit per length, and each individual circuit is
 * still finite and legal. Any lower bound proved against non-uniform circuits
 * is therefore a genuinely stronger statement than one against algorithms.
 */
(function (root, factory) {
  const scope = typeof window !== 'undefined' ? window : null;
  const api = factory();
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  if (scope) scope.Circuits = api;
}(this, function () {
  'use strict';

  const GATES = ['and', 'or', 'not', 'xor', 'input', 'const'];

  /**
   * A circuit is a list of gates in topological order. Each is
   * `{ id, op, inputs }` where `inputs` are earlier ids, and the output is the
   * last gate unless `output` says otherwise.
   */
  function create(config) {
    return {
      gates: config.gates.slice(),
      inputs: config.inputs,
      output: config.output === undefined ? config.gates[config.gates.length - 1].id
        : config.output,
      label: config.label || null
    };
  }

  const OPS = {
    and: function (values) { return values.every(Boolean) ? 1 : 0; },
    or: function (values) { return values.some(Boolean) ? 1 : 0; },
    not: function (values) { return values[0] ? 0 : 1; },
    xor: function (values) {
      return values.reduce(function (acc, v) { return acc ^ v; }, 0);
    }
  };

  function evaluate(circuit, bits) {
    const values = {};

    circuit.gates.forEach(function (gate) {
      if (gate.op === 'input') { values[gate.id] = bits[gate.index] ? 1 : 0; return; }
      if (gate.op === 'const') { values[gate.id] = gate.value; return; }
      values[gate.id] = OPS[gate.op](gate.inputs.map(function (id) { return values[id]; }));
    });
    return values[circuit.output];
  }

  /* ------------------------------------------------------- size and depth */

  /** Size is the gate count excluding inputs and constants — the area. */
  function size(circuit) {
    return circuit.gates.filter(function (gate) {
      return gate.op !== 'input' && gate.op !== 'const';
    }).length;
  }

  /**
   * Depth is the longest path from an input to the output — the latency,
   * because every gate on that path must settle before the next one can.
   */
  function depth(circuit) {
    const levels = {};

    circuit.gates.forEach(function (gate) {
      if (gate.op === 'input' || gate.op === 'const') { levels[gate.id] = 0; return; }
      levels[gate.id] = 1 + Math.max.apply(null, gate.inputs.map(function (id) {
        return levels[id];
      }));
    });
    return levels[circuit.output];
  }

  /** Gates grouped by level, which is what the picture draws and what the
   *  parallel-time reading means: level k can all fire at once. */
  function layers(circuit) {
    const levels = {};
    const rows = [];

    circuit.gates.forEach(function (gate) {
      const level = gate.op === 'input' || gate.op === 'const' ? 0
        : 1 + Math.max.apply(null, gate.inputs.map(function (id) { return levels[id]; }));

      levels[gate.id] = level;
      if (!rows[level]) rows[level] = [];
      rows[level].push(gate);
    });
    return rows;
  }

  /** The truth table, which is how correctness is asserted rather than
   *  argued — every input, exhaustively, for the widths this section uses. */
  function truthTable(circuit, n) {
    const rows = [];

    for (let mask = 0; mask < Math.pow(2, n); mask += 1) {
      const bits = [];

      for (let i = 0; i < n; i += 1) bits.push((mask >> i) & 1);
      rows.push({ bits: bits, output: evaluate(circuit, bits) });
    }
    return rows;
  }

  function computes(circuit, n, reference) {
    return truthTable(circuit, n).every(function (row) {
      return row.output === (reference(row.bits) ? 1 : 0);
    });
  }

  /* ---------------------------------------------------------- the families */

  function inputs(n) {
    const gates = [];

    for (let i = 0; i < n; i += 1) gates.push({ id: 'x' + i, op: 'input', index: i });
    return gates;
  }

  /**
   * OR of n bits, as a chain: minimum size and maximum depth. This is the
   * sequential shape — n − 1 gates, n − 1 deep.
   */
  function orChain(n) {
    const gates = inputs(n);
    let last = 'x0';

    for (let i = 1; i < n; i += 1) {
      gates.push({ id: 'g' + i, op: 'or', inputs: [last, 'x' + i] });
      last = 'g' + i;
    }
    return create({ gates: gates, inputs: n, output: last,
      label: 'OR of ' + n + ' bits, as a chain' });
  }

  /**
   * The same function as a balanced tree: the same size and logarithmic depth.
   * Nothing was traded away — the chain was simply worse, which is the first
   * thing to notice before the real trades.
   */
  function orTree(n) {
    const gates = inputs(n);
    let level = [];
    let counter = 0;

    for (let i = 0; i < n; i += 1) level.push('x' + i);
    while (level.length > 1) {
      const next = [];

      for (let i = 0; i < level.length; i += 2) {
        if (i + 1 === level.length) { next.push(level[i]); continue; }
        const id = 'g' + counter;

        counter += 1;
        gates.push({ id: id, op: 'or', inputs: [level[i], level[i + 1]] });
        next.push(id);
      }
      level = next;
    }
    return create({ gates: gates, inputs: n, output: level[0],
      label: 'OR of ' + n + ' bits, as a tree' });
  }

  /**
   * OR of n bits in DEPTH 2, by an unbounded fan-in gate — this is the AC⁰
   * model, where a single gate may take any number of inputs. Constant depth
   * is only possible with unbounded fan-in, which is why AC⁰ is defined that
   * way and why the class is about parallel time rather than about gate count.
   */
  function orFlat(n) {
    const gates = inputs(n);

    gates.push({ id: 'out', op: 'or',
      inputs: gates.map(function (gate) { return gate.id; }) });
    return create({ gates: gates, inputs: n, output: 'out',
      label: 'OR of ' + n + ' bits, unbounded fan-in' });
  }

  /**
   * PARITY of n bits — the function that is NOT in AC⁰, proved by Furst,
   * Saxe and Sipser and then tightly by Håstad. As a chain of XOR gates it is
   * linear size and linear depth; as a tree, linear size and logarithmic
   * depth; and there is no constant-depth polynomial-size family at all,
   * however you arrange it.
   */
  function parityChain(n) {
    const gates = inputs(n);
    let last = 'x0';

    for (let i = 1; i < n; i += 1) {
      gates.push({ id: 'p' + i, op: 'xor', inputs: [last, 'x' + i] });
      last = 'p' + i;
    }
    return create({ gates: gates, inputs: n, output: last,
      label: 'PARITY of ' + n + ' bits, as a chain' });
  }

  function parityTree(n) {
    const gates = inputs(n);
    let level = [];
    let counter = 0;

    for (let i = 0; i < n; i += 1) level.push('x' + i);
    while (level.length > 1) {
      const next = [];

      for (let i = 0; i < level.length; i += 2) {
        if (i + 1 === level.length) { next.push(level[i]); continue; }
        const id = 'p' + counter;

        counter += 1;
        gates.push({ id: id, op: 'xor', inputs: [level[i], level[i + 1]] });
        next.push(id);
      }
      level = next;
    }
    return create({ gates: gates, inputs: n, output: level[0],
      label: 'PARITY of ' + n + ' bits, as a tree' });
  }

  /**
   * A ripple-carry adder's carry chain: depth linear in the width, which is
   * exactly the latency a real ripple-carry ALU has.
   */
  function rippleCarry(n) {
    const gates = inputs(2 * n);
    let carry = null;

    for (let i = 0; i < n; i += 1) {
      const a = 'x' + i;
      const b = 'x' + (n + i);
      const and = 'a' + i;
      const or = 'o' + i;

      gates.push({ id: and, op: 'and', inputs: [a, b] });
      if (carry === null) { carry = and; continue; }
      const propagate = 'p' + i;
      const both = 'c' + i;

      gates.push({ id: propagate, op: 'or', inputs: [a, b] });
      gates.push({ id: both, op: 'and', inputs: [propagate, carry] });
      gates.push({ id: or, op: 'or', inputs: [and, both] });
      carry = or;
    }
    return create({ gates: gates, inputs: 2 * n, output: carry,
      label: 'ripple-carry out of ' + n + ' bits' });
  }

  /**
   * The same carry, computed with unbounded fan-in in depth 2 — carry
   * lookahead. Bigger and shallower, which is the trade the section is about
   * and which M33 makes in silicon.
   */
  function carryLookahead(n) {
    const gates = inputs(2 * n);
    const terms = [];

    for (let i = 0; i < n; i += 1) {
      const generate = 'g' + i;

      gates.push({ id: generate, op: 'and', inputs: ['x' + i, 'x' + (n + i)] });
      const chain = [generate];

      for (let j = i + 1; j < n; j += 1) {
        const propagate = 'p' + i + '_' + j;

        gates.push({ id: propagate, op: 'or', inputs: ['x' + j, 'x' + (n + j)] });
        chain.push(propagate);
      }
      const term = 't' + i;

      gates.push({ id: term, op: 'and', inputs: chain });
      terms.push(term);
    }
    gates.push({ id: 'out', op: 'or', inputs: terms });
    return create({ gates: gates, inputs: 2 * n, output: 'out',
      label: 'carry-lookahead out of ' + n + ' bits' });
  }

  /* ---------------------------------------------------------- the growth */

  /**
   * Size and depth against width for a family, which is the measurement the
   * section reports. Correctness is checked exhaustively at each width, so a
   * family that grows nicely and computes the wrong thing is caught.
   */
  function growth(builder, widths, reference) {
    return widths.map(function (n) {
      const circuit = builder(n);

      return { n: n, size: size(circuit), depth: depth(circuit),
        correct: reference ? computes(circuit, circuit.inputs, reference(n)) : null,
        label: circuit.label };
    });
  }

  /** OR, PARITY and the two adders, as reference functions over the bits. */
  function references() {
    return {
      or: function () {
        return function (bits) { return bits.some(Boolean); };
      },
      parity: function () {
        return function (bits) {
          return bits.reduce(function (acc, b) { return acc ^ b; }, 0) === 1;
        };
      },
      carry: function (n) {
        return function (bits) {
          let carry = 0;

          for (let i = 0; i < n; i += 1) {
            const sum = bits[i] + bits[n + i] + carry;

            carry = sum >= 2 ? 1 : 0;
          }
          return carry === 1;
        };
      }
    };
  }

  function families() {
    return { orChain: orChain, orTree: orTree, orFlat: orFlat,
      parityChain: parityChain, parityTree: parityTree,
      rippleCarry: rippleCarry, carryLookahead: carryLookahead };
  }

  /** The class table, which is where the parallel reading lives. */
  const CLASSES = [
    { name: 'AC⁰', depth: 'constant', fanIn: 'unbounded', size: 'polynomial',
      contains: 'OR, AND, threshold-free comparisons',
      excludes: 'PARITY — proved, and one of the few unconditional lower bounds we have' },
    { name: 'AC¹', depth: 'O(log n)', fanIn: 'unbounded', size: 'polynomial',
      contains: 'PARITY, and reachability', excludes: 'nothing known' },
    { name: 'NC¹', depth: 'O(log n)', fanIn: 'bounded (2)', size: 'polynomial',
      contains: 'PARITY, addition, regular languages',
      excludes: 'nothing known — NC¹ ⊆ L is not known to be strict' },
    { name: 'NC', depth: 'polylogarithmic', fanIn: 'bounded', size: 'polynomial',
      contains: 'matrix multiplication, sorting, determinant',
      excludes: 'P-complete problems, unless NC = P' },
    { name: 'P/poly', depth: 'any', fanIn: 'bounded', size: 'polynomial',
      contains: 'all of P, and some UNDECIDABLE languages',
      excludes: 'anything needing superpolynomial size — and we cannot prove any explicit example' }
  ];

  return {
    GATES: GATES, CLASSES: CLASSES,
    create: create, evaluate: evaluate, size: size, depth: depth, layers: layers,
    truthTable: truthTable, computes: computes, growth: growth, references: references,
    families: families,
    orChain: orChain, orTree: orTree, orFlat: orFlat,
    parityChain: parityChain, parityTree: parityTree,
    rippleCarry: rippleCarry, carryLookahead: carryLookahead
  };
}));
